package de.fzi.ipe.uapp.infoframe;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;

import javax.imageio.ImageIO;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * This servlet only returns the image, generated by the infoframe.
 * @author Sebastian Schoebinger
 *
 */

public class ResourceServlet extends HttpServlet {
	
	@Override
	protected void doGet(HttpServletRequest req, HttpServletResponse resp)
			throws ServletException, IOException {
		// TODO Auto-generated method stub
		resp.setHeader("Refresh", "30");
		BufferedImage image = ImageIO.read(new File(System.getenv("systemdrive")+"/rss/rssimg.jpeg"));
		OutputStream out = resp.getOutputStream();
		ImageIO.write(image, "jpeg", out);
		out.flush();
	}
	
}
